"""Produce an accessible self-contained test-kit page from measured controls.

No canonical URL or public Dataset identifier is guessed. Root may pass an actual
publication URL only after selecting the final public destination.
"""
from __future__ import annotations
import argparse
import html
import json
from pathlib import Path
from urllib.parse import urlparse
from build_browser_section import browser_section

ROOT = Path(__file__).resolve().parent

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--publication-url")
    args = parser.parse_args()
    if args.publication_url and (urlparse(args.publication_url).scheme != "https" or not urlparse(args.publication_url).netloc):
        raise ValueError("Actual publication URL must be HTTPS.")
    result = json.loads((ROOT / "results/generated-controls-measured.json").read_text(encoding="utf-8"))
    manifest = json.loads((ROOT / "manifest.json").read_text(encoding="utf-8"))
    rows = []
    names = {
        "reference-a4": "A4 reference",
        "reference-letter": "Letter reference",
        "a4-uniform-95-percent": "A4: uniform 95% control",
        "letter-uniform-95-percent": "Letter: uniform 95% control",
        "a4-anisotropic-96x104-percent": "A4: 96% width / 104% height control",
        "a4-to-letter-whole-paper-fit-model": "A4 to Letter: whole-paper fit model",
    }
    for entry in result["results"]:
        square = next(item for item in entry["metrics"] if item["marker"] == "metric-square")
        label = names[entry["case_id"]]
        origin = "Reference input" if entry["origin"] == "programmatic-reference" else "Known software transform"
        rows.append(f'<tr><th scope="row"><a href="{html.escape(entry["path"], quote=True)}">{html.escape(label)}</a></th><td>{origin}</td><td>{square["width_mm"]:.5f} mm</td><td>{square["height_mm"]:.5f} mm</td><td>{square["error_x_percent"]:+.5f}% / {square["error_y_percent"]:+.5f}%</td></tr>')
    canonical = f'<link rel="canonical" href="{html.escape(args.publication_url, quote=True)}">' if args.publication_url else ""
    browser = browser_section(ROOT)
    schema = {"@context": "https://schema.org", "@type": "CreativeWork", "name": "Sewlore PDF Geometry Test Kit: A4 and Letter", "version": "1.0.0", "dateCreated": "2026-10-10", "inLanguage": "en", "creator": {"@type":"Organization","name":"Sewlore","url":"https://sewlore.com/"}, "description": "Deterministic A4 and Letter vector fixtures with measured known-transform controls. Digital PDF geometry only; no native or physical printer results in this release."}
    if args.publication_url:
        schema["url"] = args.publication_url
    schema["description"] = f"Deterministic A4 and Letter vector fixtures, six measured known-geometry references/controls and {browser['count']} actual Chrome HTML-to-PDF outputs. Digital geometry only; no physical printer measurements."
    page = '''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>PDF Print Geometry Test Kit: A4 and Letter | Sewlore</title>
<meta name="description" content="Check horizontal and vertical PDF scale with A4 and Letter vector references, known-transform controls, raw geometry data and a reproducible analyzer.">
CANONICAL
<style>
:root{color-scheme:light;--ink:#18332e;--muted:#53685f;--cream:#f7f5ef;--line:#c6d3cb;--accent:#006b5a}*{box-sizing:border-box}body{margin:0;background:var(--cream);color:var(--ink);font:18px/1.6 system-ui,sans-serif}a{color:var(--accent);text-underline-offset:.2em}a:focus-visible,summary:focus-visible{outline:3px solid #ab4600;outline-offset:4px}.skip{position:absolute;top:-100px;left:12px}.skip:focus{top:12px;background:white;padding:12px}header,main,footer{max-width:1120px;margin:auto;padding:36px 24px}header{padding-top:55px}h1{max-width:900px;font-size:clamp(2.3rem,5vw,4.2rem);line-height:1.08;letter-spacing:-.04em;margin:.4em 0}h2{font-size:1.8rem;margin-top:1.4em}.eyebrow{font-size:.85rem;text-transform:uppercase;letter-spacing:.15em;color:var(--muted)}.lead{font-size:1.25rem;max-width:870px}.status{padding:18px 22px;border-left:5px solid var(--accent);background:#e7eee7;border-radius:4px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:22px}.card{background:white;border:1px solid var(--line);border-radius:14px;padding:25px}.card h2{margin-top:0}.download{display:inline-block;background:var(--ink);color:white;border-radius:6px;padding:10px 16px;margin:6px 8px 6px 0;text-decoration:none}.small{font-size:.94rem;color:var(--muted)}.table-wrap{overflow-x:auto;border:1px solid var(--line);background:white;border-radius:10px}table{border-collapse:collapse;min-width:800px;width:100%;font-size:.95rem}caption{text-align:left;padding:18px;font-weight:600}th,td{padding:14px 16px;text-align:left;border-top:1px solid var(--line);vertical-align:top}thead th{background:#e7eee7}code{font-size:.9em;background:#e7eee7;padding:2px 5px}pre{white-space:pre-wrap;background:#e7eee7;padding:18px;border-radius:8px;overflow-wrap:anywhere}li{margin:.45em 0}footer{border-top:1px solid var(--line);font-size:.95rem}.diagram{width:100%;height:auto;max-width:430px}details{border:1px solid var(--line);padding:18px;border-radius:8px}summary{cursor:pointer;font-weight:600}@media(max-width:720px){.grid{grid-template-columns:1fr}header,main,footer{padding:24px 18px}}@media print{body{background:white;font-size:11pt}header,main,footer{padding:10px 0}h1{font-size:26pt}.table-wrap{overflow:visible}table{min-width:0}.download,.skip{display:none}.card{break-inside:avoid}a{color:inherit}.status{background:white}}
</style><script type="application/ld+json">SCHEMA</script></head>
<body><a class="skip" href="#main">Skip to content</a>
<header><div class="eyebrow">Sewlore / technical reference / version 1.0.0</div><h1>Check both axes.<br>Then check the paper.</h1><p class="lead">A reproducible PDF geometry kit for understanding scale changes in sewing pattern print workflows. Start with known A4 and Letter references, then compare the geometry of an actual saved output.</p><p class="status"><strong>This release measures digital reference files and known software transforms.</strong> Native browser print experiments completed: 0. Physical printer measurements: 0. The controls below are not observations of Chrome or a printer.</p></header>
<main id="main"><section aria-labelledby="references"><h2 id="references">Download a known reference</h2><div class="grid"><article class="card"><h2>A4</h2><p>210 x 297 mm, portrait, one page.</p><a class="download" href="fixtures/sewlore-print-geometry-a4.pdf">A4 reference PDF</a><p class="small">100 mm square, 2 in x 1 in rectangle, 180 mm line and a 5 mm inset border.</p></article><article class="card"><h2>US Letter</h2><p>215.9 x 279.4 mm, portrait, one page.</p><a class="download" href="fixtures/sewlore-print-geometry-letter.pdf">Letter reference PDF</a><p class="small">The same measurement paths on a different page size. The source file is an input, not a printer result.</p></article></div></section>
<section aria-labelledby="measure"><h2 id="measure">Measure independent directions</h2><div class="grid"><div><p>A square can shrink equally in two directions, or change width and height by different amounts. Extract both axes rather than inferring one from the other.</p><p><strong>Scale ratio</strong> = output length / reference length.<br><strong>Signed error (%)</strong> = 100 x (output - reference) / reference.</p><p>Measure the path centre line. Line thickness, screen zoom and screenshot pixels are different quantities. Use a physical ruler to check a real print.</p></div><div class="card"><svg class="diagram" viewBox="0 0 430 260" role="img" aria-labelledby="diagram-title diagram-desc"><title id="diagram-title">Uniform and unequal scale changes</title><desc id="diagram-desc">Illustrative diagram comparing a square with a 95 percent uniformly reduced square and a rectangle with 96 percent width and 104 percent height.</desc><rect x="25" y="40" width="100" height="100" fill="none" stroke="#006b5a" stroke-width="2"/><rect x="165" y="40" width="95" height="95" fill="none" stroke="#006b5a" stroke-width="2"/><rect x="305" y="40" width="96" height="104" fill="none" stroke="#006b5a" stroke-width="2"/><g font-family="system-ui,sans-serif" font-size="13" fill="#18332e"><text x="25" y="172">100 x 100</text><text x="165" y="172">95 x 95</text><text x="305" y="172">96 x 104</text><text x="25" y="195">Reference</text><text x="165" y="195">Uniform</text><text x="305" y="195">Unequal axes</text><text x="25" y="232">Illustration only; this diagram is not a calibration ruler.</text></g></svg></div></div></section>
<section aria-labelledby="controls"><h2 id="controls">Measured detector controls</h2><p>These dimensions were extracted from generated vector paths and checked against their explicitly specified transforms. Numerical tolerance: 0.005 mm. That tolerance is not a physical printer accuracy claim.</p><div class="table-wrap"><table><caption>100 mm square: generated inputs and known-transform controls</caption><thead><tr><th scope="col">File</th><th scope="col">Evidence class</th><th scope="col">Extracted width</th><th scope="col">Extracted height</th><th scope="col">Width / height error</th></tr></thead><tbody>ROWS</tbody></table></div><p><a href="results/generated-controls-measured.csv">Download extracted geometry CSV</a> · <a href="expected-geometry.csv">Expected geometry CSV</a> · <a href="results/generated-controls-measured.json">Full measurement JSON</a> · <a href="manifest.json">Versioned file hashes and units</a></p><details><summary>What the A4-to-Letter model assumes</summary><p>The whole-paper model uses min(215.9 / 210, 279.4 / 297), with no margins or printer restrictions. Its scale is about 94.0741%. It is a mathematical control, not an observed print setting result. A printable-area fit can differ.</p></details></section>
<section aria-labelledby="native"><h2 id="native">Run an actual software comparison</h2><ol><li>Open the PDF reference in the application you want to test.</li><li>Open the visible print UI. Record the exact application, destination, paper, orientation and scale labels. Capture a settings screenshot.</li><li>Save the actual output. Keep the original PDF and screenshot, including SHA-256 hashes.</li><li>Inspect width and height independently, then visually review clipping and page boundaries.</li></ol><p><strong>Destination matters.</strong> Chromium documents a source-size path for Save as PDF. It can retain the PDF's original page size, which is different from printing to a PDF printer destination. If the UI does not expose paper or scale controls, record that fact instead of inventing applied settings.</p><p>Suggested cases: matched A4 at Actual size; matched Letter at Actual size; A4 to Letter at Fit to paper; Letter to A4 at Fit to paper. Use only controls that actually exist in the captured destination.</p><p>No native outcome is listed until a real output and settings receipt have been measured.</p></section>
<section aria-labelledby="reproduce"><h2 id="reproduce">Reproduce the geometry checks</h2><p>The generator and analyzer are downloadable Python scripts. Their control results should not be mistaken for an application benchmark.</p><pre><code>python build_atlas.py
python inspect_pdf_geometry.py --all-generated
python inspect_pdf_geometry.py --native-receipt incoming/your-case.receipt.json</code></pre><p><a href="build_atlas.py">Reference/control generator</a> · <a href="inspect_pdf_geometry.py">Vector geometry analyzer</a> · <a href="methodology.md">Full method and limitations</a> · <a href="environment.json">Preparation environment</a></p><p>The analyzer reports missing or rasterized markers as unextractable. Raw path extents do not prove visibility after clipping. It does not guess missing dimensions or characterize a physical printer.</p></section>
<section aria-labelledby="sources"><h2 id="sources">Read the methods behind the settings</h2><ul><li><a href="https://support.google.com/chrome/answer/1069693?hl=en">Google Chrome: print workflow</a></li><li><a href="https://helpx.adobe.com/acrobat/desktop/print-documents/set-up-and-print-pdfs/page-size.html">Adobe Acrobat: Fit and Actual size definitions</a></li><li><a href="https://chromium.googlesource.com/chromium/src/+/f6529c7990744370869e4ab2794caae6c46ba044/components/printing/renderer/print_render_frame_helper.cc">Chromium: source-size and print scaling implementation</a></li><li><a href="https://sewlore.com/pages/printing-assembly">Sewlore: printing and assembly guide</a></li><li><a href="https://sewlore.com/pages/pdf-pattern-print-scale-checker">Sewlore: compare a physically measured test square</a></li></ul><p>For sewing patterns, check one actual test page before printing the full file. Confirm the pattern's own instructions and measure your printed page.</p></section></main>
<footer><p><strong>Sewlore PDF Geometry Test Kit, v1.0.0.</strong> Prepared 2026-10-10. Original technical resource with AI assistance and programmatic verification. Digital PDF geometry only; no peer-review, independent laboratory validation or physical print results claimed.</p><p>When citing this resource, include Sewlore, the title, version, date and the actual public URL. <a href="https://sewlore.com/">Visit Sewlore</a>.</p></footer></body></html>'''
    page = page.replace("CANONICAL", canonical).replace("SCHEMA", json.dumps(schema, ensure_ascii=False).replace("</", "<\\/")).replace("ROWS", "\n".join(rows))
    original_status = '<strong>This release measures digital reference files and known software transforms.</strong> Native browser print experiments completed: 0. Physical printer measurements: 0. The controls below are not observations of Chrome or a printer.'
    page = page.replace(original_status,browser["status"]).replace('<section aria-labelledby="controls">',browser["section"]+'\n<section aria-labelledby="controls">')
    page = page.replace('<div class="table-wrap"><table><caption>100 mm square:','<div class="table-wrap" tabindex="0" role="region" aria-label="Generated detector controls"><table><caption>100 mm square:')
    (ROOT / "index.html").write_text(page, encoding="utf-8")
    (ROOT / "public-page-validation.private.json").write_text(json.dumps({"schema_version":1,"generated_rows":len(rows),"browser_engine_rows":browser["count"],"native_pdf_viewer_rows":0,"canonical_url":args.publication_url,"title":"PDF Print Geometry Test Kit: A4 and Letter | Sewlore","source_href":"https://sewlore.com/pages/printing-assembly","includes_source_hash_manifest":True,"native_and_physical_limitations_visible":True,"programmatic_controls_labeled":True,"public_url_not_assumed":not bool(args.publication_url)}, indent=2)+"\n",encoding="utf-8")
    print(json.dumps({"page":str(ROOT/"index.html"),"generated_rows":len(rows),"browser_engine_rows":browser["count"],"native_pdf_viewer_rows":0}))

if __name__ == "__main__":
    main()
