"""Prepare original exact-unit HTML/SVG sources; does not run a browser."""
from __future__ import annotations
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PAPER = {"a4":(210.0,297.0),"letter":(215.9,279.4)}

def main():
    fixtures = []
    for paper,(w,h) in PAPER.items():
        y_square = h - 210
        y_inch = h - 94.4
        y_line = h - 48
        text = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,follow">
<title>Sewlore HTML Geometry Reference - {paper.upper()}</title>
<style>@page{{size:{w:g}mm {h:g}mm;margin:0}}*{{box-sizing:border-box}}html,body{{margin:0;padding:0;width:{w:g}mm;height:{h:g}mm;line-height:0}}svg{{display:block;width:{w:g}mm;height:{h:g}mm;break-inside:avoid;page-break-inside:avoid}}text{{font-family:Arial,Helvetica,sans-serif;fill:#18332e}}a{{fill:#18332e}}@media screen{{body{{background:#e8eee8}}svg{{background:white}}}}@media print{{html,body{{background:white}}}}</style></head><body>
<svg xmlns="http://www.w3.org/2000/svg" width="{w:g}mm" height="{h:g}mm" viewBox="0 0 {w:g} {h:g}" role="img" aria-labelledby="title desc">
<title id="title">Sewlore exact-unit HTML geometry fixture, {paper.upper()}</title><desc id="desc">A known 100 mm square, a 2 inch by 1 inch rectangle, and a 180 mm line. This HTML is a browser input. Its source dimensions are not an observation of printed output.</desc>
<rect x="5" y="5" width="{w-10:g}" height="{h-10:g}" fill="none" stroke="#97aaa4" stroke-width="0.1058333333"/>
<text x="20" y="23" font-size="6.35" font-weight="700">SEWLORE / HTML GEOMETRY</text>
<text x="20" y="32" font-size="3.527777778">{paper.upper()} source | {w:g} x {h:g} mm | version 1.0</text>
<text x="20" y="42" font-size="3.175">Exact CSS/SVG dimensions. Browser output must be measured separately.</text>
<text x="20" y="48" font-size="3.175">Digital input only. Not a PDF-viewer print setting or physical printer test.</text>
<rect x="30" y="{y_square:g}" width="100" height="100" fill="none" stroke="rgb(0%,45%,38%)" stroke-width="0.15875"/>
<text x="40" y="{y_square+47:g}" font-size="4.233333333" font-weight="700">100 mm x 100 mm</text>
<text x="40" y="{y_square+55:g}" font-size="3.175">Green path: metric-square</text>
<text x="40" y="{y_square+62:g}" font-size="3.175">Width and height are separate checks.</text>
<rect x="30" y="{y_inch:g}" width="50.8" height="25.4" fill="none" stroke="rgb(7%,31%,59%)" stroke-width="0.15875"/>
<text x="90" y="{h-85:g}" font-size="3.527777778" font-weight="700">2 in x 1 in</text>
<text x="90" y="{h-79:g}" font-size="3.175">50.8 mm x 25.4 mm</text>
<text x="90" y="{h-73:g}" font-size="3.175">Blue path: inch-rectangle</text>
<line x1="15" y1="{y_line:g}" x2="195" y2="{y_line:g}" stroke="rgb(80%,35%,2%)" stroke-width="0.15875"/>
<text x="105" y="{h-42:g}" text-anchor="middle" font-size="3.175">Orange path: long-horizontal | 180 mm</text>
<text x="20" y="{h-21:g}" font-size="2.469444444">Inset border: 5 mm from source edges. Inspect output clipping visually.</text>
<a href="https://sewlore.com/pages/printing-assembly"><text x="20" y="{h-16:g}" font-size="2.469444444">Methods: sewlore.com/pages/printing-assembly</text></a>
</svg></body></html>'''
        path = ROOT / "fixtures" / f"print-geometry-{paper}.html"
        path.write_text(text,encoding="utf-8")
        fixtures.append({"fixture_id":f"html-{paper}","path":path.relative_to(ROOT).as_posix(),"sha256":hashlib.sha256(path.read_bytes()).hexdigest(),"origin":"original-html-svg-source","css_page_width_mm":w,"css_page_height_mm":h,"reference_geometry":"same three metric/inch/long-line paths as manifest.json","document_type":"html","external_scripts_or_fonts":False})
    (ROOT / "html-fixtures-manifest.json").write_text(json.dumps({"schema_version":1,"prepared_date":"2026-10-10","scope":"Known input geometry only. No browser output is generated by this script.","fixtures":fixtures},indent=2)+"\n",encoding="utf-8")
    base = {"landscape":False,"displayHeaderFooter":False,"printBackground":True,"marginTop":0,"marginBottom":0,"marginLeft":0,"marginRight":0,"pageRanges":"","transferMode":"ReturnAsBase64"}
    cases = [
        {"case_id":"browser-html-a4-css-size-scale-100","source_fixture":"fixtures/print-geometry-a4.html","params":{**base,"scale":1,"paperWidth":210/25.4,"paperHeight":297/25.4,"preferCSSPageSize":True}},
        {"case_id":"browser-html-letter-css-size-scale-100","source_fixture":"fixtures/print-geometry-letter.html","params":{**base,"scale":1,"paperWidth":8.5,"paperHeight":11,"preferCSSPageSize":True}},
        {"case_id":"browser-html-a4-to-letter-prefercss-false","source_fixture":"fixtures/print-geometry-a4.html","params":{**base,"scale":1,"paperWidth":8.5,"paperHeight":11,"preferCSSPageSize":False}},
        {"case_id":"browser-html-a4-css-size-scale-95","source_fixture":"fixtures/print-geometry-a4.html","params":{**base,"scale":.95,"paperWidth":210/25.4,"paperHeight":297/25.4,"preferCSSPageSize":True}},
    ]
    (ROOT / "browser-engine-cases.private.json").write_text(json.dumps({"schema_version":1,"command":"Page.printToPDF","status":"planned-not-run","operator":"root-only-documented-CUA-CDP-capability","scope":"Chrome HTML-to-PDF developer print output; not PDF-viewer Actual size/Fit or physical printer results","documentation_url":"https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF","cases":cases},indent=2)+"\n",encoding="utf-8")
    print(json.dumps({"html_fixtures":2,"planned_browser_engine_cases":4,"actual_browser_outputs":0}))

if __name__ == "__main__":
    main()
